from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, AsyncIterator, Optional


class TTSError(Exception):
    """Base exception for all TTS errors."""
    def __init__(self, message: str, error_code: str = "TTS_ERROR", details: Optional[str] = None) -> None:
        super().__init__(message)
        self.message = message
        self.error_code = error_code
        self.details = details


class TTSAuthenticationError(TTSError):
    """Raised when TTS provider authentication fails or credentials are missing."""
    def __init__(self, message: str = "TTS API authentication failed or credentials missing", details: Optional[str] = None) -> None:
        super().__init__(message=message, error_code="TTS_AUTH_ERROR", details=details)


class TTSAPIError(TTSError):
    """Raised when the TTS provider returns an API-level error (e.g. 400 Bad Request, 500 Internal)."""
    def __init__(self, message: str, status_code: Optional[int] = None, details: Optional[str] = None) -> None:
        self.status_code = status_code
        super().__init__(message=message, error_code="TTS_API_ERROR", details=details)


class TTSNetworkError(TTSError):
    """Raised when network connectivity fails during TTS streaming."""
    def __init__(self, message: str = "Network error connecting to TTS provider", details: Optional[str] = None) -> None:
        super().__init__(message=message, error_code="TTS_NETWORK_ERROR", details=details)


class TTSCancelledError(TTSError):
    """Raised when an ongoing TTS synthesis stream is cancelled."""
    def __init__(self, message: str = "TTS synthesis cancelled", details: Optional[str] = None) -> None:
        super().__init__(message=message, error_code="TTS_CANCELLED", details=details)


@dataclass
class TTSChunk:
    """
    A chunk of streaming audio output generated by a TTSProvider.
    """
    audio_bytes: bytes
    chunk_index: int
    format: str = "pcm"
    sample_rate: int = 16000
    is_final: bool = False
    request_id: Optional[str] = None


class TTSProvider(ABC):
    """
    Abstract interface for VoiceForm text-to-speech providers.
    Decouples VoiceForm from specific TTS engine implementations (Rime, Mock, etc.).
    """

    @abstractmethod
    def synthesize_stream(
        self,
        text: str,
        session_id: Optional[str] = None,
        request_id: Optional[str] = None,
        speaker: Optional[str] = None,
        **kwargs: Any
    ) -> AsyncIterator[TTSChunk]:
        """
        Synthesizes text into a stream of audio chunks.
        Yields TTSChunk instances as audio becomes available from the provider.
        """
        pass

    @abstractmethod
    async def cancel(self, request_id: str) -> None:
        """
        Cancels an in-flight synthesis request.
        """
        pass
