/**
 * Generates a stable and unique CSS selector for a given DOM element.
 * Prioritizes ID, name within form, unique name, and hierarchical path.
 */
export function generateElementSelector(element: HTMLElement): string {
  // 1. Direct ID if valid and unique in document
  if (element.id && isValidId(element.id)) {
    const escapedId = CSS.escape(element.id);
    if (document.querySelectorAll(`#${escapedId}`).length === 1) {
      return `#${escapedId}`;
    }
  }

  // 2. Name attribute combined with tag and form context
  const name = element.getAttribute('name');
  const tagName = element.tagName.toLowerCase();
  const type = element.getAttribute('type');
  const typeAttr = type ? `[type="${CSS.escape(type)}"]` : '';

  if (name) {
    const escapedName = CSS.escape(name);
    const form = element.closest('form');
    
    if (form) {
      const formSelector = form.id && isValidId(form.id)
        ? `#${CSS.escape(form.id)}`
        : getPathToElement(form);
      
      const scopedSelector = `${formSelector} ${tagName}[name="${escapedName}"]${typeAttr}`;
      const matching = document.querySelectorAll(scopedSelector);
      if (matching.length === 1) {
        return scopedSelector;
      }
      // For radio buttons or arrays with identical names
      if (matching.length > 1) {
        for (let i = 0; i < matching.length; i++) {
          if (matching[i] === element) {
            // For radio inputs, check value attribute first
            const val = element.getAttribute('value');
            if (val) {
              const valSelector = `${scopedSelector}[value="${CSS.escape(val)}"]`;
              if (document.querySelectorAll(valSelector).length === 1) {
                return valSelector;
              }
            }
            return `${scopedSelector}:nth-of-type(${i + 1})`;
          }
        }
      }
    } else {
      // Orphan field outside form
      const globalSelector = `${tagName}[name="${escapedName}"]${typeAttr}`;
      const matching = document.querySelectorAll(globalSelector);
      if (matching.length === 1) {
        return globalSelector;
      }
      if (matching.length > 1) {
        for (let i = 0; i < matching.length; i++) {
          if (matching[i] === element) {
            const val = element.getAttribute('value');
            if (val) {
              const valSelector = `${globalSelector}[value="${CSS.escape(val)}"]`;
              if (document.querySelectorAll(valSelector).length === 1) {
                return valSelector;
              }
            }
            return `${globalSelector}:nth-of-type(${i + 1})`;
          }
        }
      }
    }
  }

  // 3. Fallback to structural path
  return getPathToElement(element);
}

function isValidId(id: string): boolean {
  if (!id || id.trim() === '') return false;
  // Ignore purely dynamic IDs generated by some frameworks (e.g. :r1:, dynamic guids)
  // But allow if valid and uniquely resolvable
  return true;
}

function getPathToElement(element: Element): string {
  if (element.id && isValidId(element.id)) {
    const escaped = `#${CSS.escape(element.id)}`;
    if (document.querySelectorAll(escaped).length === 1) {
      return escaped;
    }
  }

  const path: string[] = [];
  let current: Element | null = element;

  while (current && current !== document.body && current !== document.documentElement) {
    const tagName = current.tagName.toLowerCase();
    const parent: HTMLElement | null = current.parentElement;
    
    if (current.id && isValidId(current.id)) {
      const escapedId = `#${CSS.escape(current.id)}`;
      if (document.querySelectorAll(escapedId).length === 1) {
        path.unshift(escapedId);
        break;
      }
    }

    if (!parent) {
      path.unshift(tagName);
      break;
    }

    const siblings = Array.from(parent.children).filter(el => el.tagName === current!.tagName);
    if (siblings.length > 1) {
      const index = siblings.indexOf(current) + 1;
      path.unshift(`${tagName}:nth-of-type(${index})`);
    } else {
      path.unshift(tagName);
    }

    current = parent;
  }

  return path.join(' > ');
}
